const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1596574611000,
      duration: 5400000,
      id: '272364766',
      name: 'Co-Lunch: inspirierender Austausch & Netzwerken in der Mittagspause',
      rsvp_limit: 11,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1597919400000,
      local_date: '2020-08-20',
      local_time: '12:30',
      updated: 1596574611000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
      id: 26846459,
      name: 'togather',
      lat: 48.137943267822266,
      lon: 11.543676376342773,
      repinned: true,
      address_1: 'Schwanthalerstraße 160',
      city: 'München',
      country: 'DE',
      localized_country_name: 'Deutschland'
      },
      is_online_event: false,
      group: {
      created: 1538836714000,
      name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
      id: 30090989,
      join_mode: 'open',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'Co-Dining',
      who: 'Netzwerkerinnen und Netzwerker',
      localized_location: 'München, Deutschland',
      state: '',
      country: 'de',
      region: 'de_DE',
      timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/de-DE/Co-Dining/events/272364766/',
      description: '<p>Das Wort Co ist Englisch für Mit(einander). Schwierig in Zeiten von Corona. Doch die neuen Auflagen erlauben wieder ein Zusammenkommen von bis zu 10 Personen am großen Tisch.</p> <p>Ich freue mich über jeden der Lust auf Austausch und Kommunikation hat. Auf ein herzliches Miteinander, auf gemeinsamen Genuss und einen inspirierenden Austausch.</p> <p>DISCLAIMER: Wenn du dich nicht gut fühlst, befürchtest krank zu sein oder dich nicht gut mit dem Gedanken stellst mit mehreren Menschen an einem Tisch zu sitzen, dann ist dieser Co-Lunch leider nicht für deine Teilnahmen geeignet.</p> <p>Wie immer, der Co-Lunch hat keine Agenda. Ich werde nichts moderieren. Ich biete den Raum für Gespräche und ein Miteinander.</p> <p>Eure Sarah</p> <p>P.S. Die Veranstaltung ist auf 10 Personen begrenzt. Bitte nur anmelden, wenn du tatsächlich kommt. Wenn dir doch was dazwischen kommt, bitte wieder abmelden.</p>',
      how_to_find_us: 'am großen dreieckigen Co-Dining Tisch',
      visibility: 'public',
      member_pay_fee: false
      },
      {
      created: 1596574291000,
      duration: 7200000,
      id: '272364682',
      name: 'Endlich wieder Socializing Dinner',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1598029200000,
      local_date: '2020-08-21',
      local_time: '19:00',
      updated: 1596574291000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      venue: {
      id: 26846459,
      name: 'togather',
      lat: 48.137943267822266,
      lon: 11.543676376342773,
      repinned: true,
      address_1: 'Schwanthalerstraße 160',
      city: 'München',
      country: 'DE',
      localized_country_name: 'Deutschland'
      },
      is_online_event: false,
      group: {
      created: 1538836714000,
      name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
      id: 30090989,
      join_mode: 'open',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'Co-Dining',
      who: 'Netzwerkerinnen und Netzwerker',
      localized_location: 'München, Deutschland',
      state: '',
      country: 'de',
      region: 'de_DE',
      timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/de-DE/Co-Dining/events/272364682/',
      description: '<p>Ausgehen, neue Leute Kennenlernen und feiern. Wir haben es alle lange gemisst.</p> <p>Am Freitagabend ist es endlich soweit wir wollen uns wieder treffen. Gutes Essen genießen und ein geselliges Miteinander erleben. Wer dabei sein möchte bitte anmelden.</p> <p>Die Anzahl der Teilnehmer ist auf 10 Personen begrenzt. Bitte deshalb nur Anmelden wer wirklich kommen kann bzw. wieder absagen, wem etwas dazwischenkommt.</p> <p>WAS DICH ERWARTET:<br/>Ich bin Gastgeberin aus Leidenschaft und glaube, dass wir zusammen mehr erreichen können. Zu diesem Zweck habe ich das togather Anfang des Jahres eröffnet.</p> <p>Wünscht du dir in einer Wohlfühlatmosphäre genussvoll und in Muße speisen zu können?</p> <p>Willst du dich in einem geselligen Rahmen mit Gleichgesinnten austauschen und dein soziales wie berufliches Netzwerk erweitern?</p> <p>Im togather lernst du neue interessante Menschen kennen, führst vielseitige Gespräche und gehst anschließend beschwingt und motiviert in deinen Tag zurück. Du gewinnst Lebensqualität durch liebevoll zubereitetes Essen in gemütlicher Atmosphäre.</p> <p>Klingt das gut? Dann bis Freitag!</p>',
      how_to_find_us: 'am großen Community Table in der Restaurant Mitte',
      visibility: 'public',
      member_pay_fee: false
      },
      {
      created: 1597689443000,
      duration: 10800000,
      id: '272639334',
      name: 'play board games',
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1598194800000,
      local_date: '2020-08-23',
      local_time: '17:00',
      rsvp_open_offset: 'PT105H',
      updated: 1597689464000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
      id: 26947718,
      name: 'Biergarten & Restaurant am Chinesischen Turm',
      lat: 48.152835845947266,
      lon: 11.592763900756836,
      repinned: true,
      address_1: 'Englischer Garten 3',
      city: 'München',
      country: 'de',
      localized_country_name: 'Deutschland'
      },
      is_online_event: false,
      group: {
      created: 1493414929000,
      name: 'Munich Social Gaming',
      id: 23474017,
      join_mode: 'open',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'Munich-Social-Gaming',
      who: 'Members',
      localized_location: 'München, Deutschland',
      state: '',
      country: 'de',
      region: 'de_DE',
      timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/de-DE/Munich-Social-Gaming/events/272639334/',
      description: '<p>Hi all,</p> <p>let\'s play our favorite games (Uno!, Coup, Dodelido, Saboteur) in a biergarten. Unlimited participants number! We rely on your help in bringing games if you have some. Looking forward to play with you!</p>',
      how_to_find_us: 'see location pin, location link in description, go ahead to find a table with games and just let us know that you\'ve came to play with us!',
      visibility: 'public',
      member_pay_fee: false
      },
      {
      created: 1596574177000,
      duration: 7200000,
      fee: {
      accepts: 'cash',
      amount: 19.9,
      currency: 'EUR',
      description: '',
      label: 'Preis',
      required: false
      },
      id: '272364660',
      name: 'Sommer Brunch',
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1598171400000,
      local_date: '2020-08-23',
      local_time: '10:30',
      updated: 1596574177000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      venue: {
      id: 26846459,
      name: 'togather',
      lat: 48.137943267822266,
      lon: 11.543676376342773,
      repinned: false,
      address_1: 'Schwanthalerstraße 160',
      city: 'München',
      country: 'DE',
      localized_country_name: 'Deutschland'
      },
      is_online_event: false,
      group: {
      created: 1538836714000,
      name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
      id: 30090989,
      join_mode: 'open',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'Co-Dining',
      who: 'Netzwerkerinnen und Netzwerker',
      localized_location: 'München, Deutschland',
      state: '',
      country: 'de',
      region: 'de_DE',
      timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/de-DE/Co-Dining/events/272364660/',
      description: '<p>Der Brunch ist der Tausendsassa aller Mahlzeiten. Er ist prädestiniert für den Sonntag, denn er beinhaltet Ausschlafen, den Freifahrtsschein schon zum Tagesbeginn mit Sekt anzustoßen, ein gemütliches Frühstück, Unmengen Kaffee, ein vollwertiges Mittagessen, unbedingt noch einen süßen Abschluss und er macht satt bis zum frühen Abend.</p> <p>Und weil der Brunch zwangsläufig über Stunden geht, ist es wichtig ihn in guter Gesellschaft zu verbringen.</p> <p>Wer also Lust hat beim Brunch neue Leute kennenzulernen, gemeinsam zu genießen und eine gesellige Zeit miteinander zu verbringen, der ist herzlich eingeladen.</p> <p>Der Bruch kostet 19,90 Euro und inkludiert:</p> <p>Gläschen Prosecco, hausgemachter Wasserkefir oder Bio-Orangensaft zur Begrüßung</p> <p>Ofenwarme Zimtschnecken und Croissant mit hausgemachter Marmelade und Ahornsirup Creme</p> <p>Breze und selbstgebackenes Brot mit Butter und hausgemachten Aufstrichen, Bio-Lachs und Merrettichcreme</p> <p>Overnight Oats mit Joghurt und fruchtiger Obstsalat</p> <p>Frisch zubereitete Bio-Eierspeise nach deiner Wahl, dazu gebratener Bio-Bacon, wenn du möchtest</p> <p>Warmer Hauptgang nach Wahl</p> <p>Überraschungsdessert</p> <p>Jeder kommt für den eigenen Verzehr auf!</p>',
      how_to_find_us: 'in der Mitte am dreieckigen Community Table',
      visibility: 'public',
      member_pay_fee: false
    },
  ]
};

export { mockEvents };
